// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ndc_231230723_de01.Models;

#nullable disable

namespace ndc_231230723_de01.Migrations
{
    [DbContext(typeof(NdcComputerContext))]
    [Migration("20251024010405_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ndc_231230723_de01.Models.NdcComputer", b =>
                {
                    b.Property<int>("ndcComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ndcComId"));

                    b.Property<string>("ndcComImage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ndcComName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("ndcComPrice")
                        .HasMaxLength(30)
                        .HasColumnType("bigint");

                    b.Property<bool>("ndcComStatus")
                        .HasMaxLength(30)
                        .HasColumnType("bit");

                    b.HasKey("ndcComId");

                    b.ToTable("NdcComputer");
                });
#pragma warning restore 612, 618
        }
    }
}
